# -*- coding: utf-8 -*-
"""key recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Otn4K7mzPveiwcfhX7E1xCDysS1FJEWz
"""

import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt

y1, sr = librosa.load("/content/drive/Shareddrives/G-33-2022/Audios/finished/Lily Allen - Everyone's At It - Multitrack/Lily Allen - Everyone's At It - Multitrack/Everyone's At It - Lead Vocals.wav")
y2, sr = librosa.load("/content/drive/Shareddrives/G-33-2022/Audios/finished/Lily Allen - Everyone's At It - Multitrack/Lily Allen - Everyone's At It - Multitrack/Everyone's At It - Piano.wav")

y=y1[1:5346243]+y2[1:5346243]
C = np.abs(librosa.cqt(y, sr=sr))

fig, ax = plt.subplots()
img = librosa.display.specshow(librosa.amplitude_to_db(C, ref=np.max),
                               sr=sr, x_axis='time', y_axis='cqt_note', ax=ax)
ax.set_title('Constant-Q power spectrum')
fig.colorbar(img, ax=ax, format="%+2.0f dB")

y1[1:5346243]

maxi  = np.max(C,0)
x = np.sum(C,1)
keys=np.reshape(x,(7,-1))
print(x.shape)
print(keys.shape)

chords = sum(keys,1)
index = np.linspace(1,12,12)
D = np.stack((index,chords),1)
D=D[D[:,1].argsort()]
print(chords.shape)
plt.plot(index,chords)
plt.show()
print(D)

D[:,1].argsort()

import matplotlib.pyplot as plt

plt.plot(x)
plt.show()

plt.hist(maxi, bins=84)
plt.title("Histogram")
plt.show()